# Generated by Django 4.0.2 on 2022-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unitType', models.CharField(choices=[('GR', 'Grams'), ('OZ', 'Ounces'), ('IT', 'Item')], default='IT', max_length=2)),
                ('unitCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventoryQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients', models.ManyToManyField(to='inventory.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=200)),
                ('menuItem', models.ManyToManyField(to='inventory.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timeCreated', models.DateTimeField(auto_now=True)),
                ('timeUpdated', models.DateTimeField(auto_now=True)),
                ('menuItems', models.ManyToManyField(to='inventory.MenuItem')),
            ],
        ),
    ]
