# Generated by Django 4.0.2 on 2022-03-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menuItems',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ManyToManyField(to='inventory.Menu'),
        ),
    ]
