# Generated by Django 4.0.2 on 2022-03-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_menuitem_menu_menuitem_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientQuantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(through='inventory.IngredientQuantity', to='inventory.Ingredient'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(through='inventory.IngredientQuantity', to='inventory.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='menuItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
        ),
    ]
