# Generated by Django 4.0.2 on 2022-03-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_menuitem_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredientQuantity',
            field=models.IntegerField(default=1),
        ),
    ]
