# Generated by Django 4.0.2 on 2022-03-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_ingredientquantity_ingredientquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishQuantity', models.IntegerField(default=0)),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem')),
            ],
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredientQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='order',
            name='menuItem',
        ),
        migrations.AddField(
            model_name='order',
            name='menuItem',
            field=models.ManyToManyField(through='inventory.DishQuantity', to='inventory.MenuItem'),
        ),
        migrations.AddField(
            model_name='dishquantity',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
        ),
    ]
