# Generated by Django 4.0.2 on 2022-03-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_dishquantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menuItem',
        ),
        migrations.AddField(
            model_name='order',
            name='menuItem',
            field=models.ManyToManyField(to='inventory.MenuItem'),
        ),
        migrations.DeleteModel(
            name='DishQuantity',
        ),
    ]
