# Generated by Django 4.0.2 on 2022-03-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_dishquantity_alter_order_menuitem_dishquantity_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='menuItem',
            new_name='menuItems',
        ),
    ]
