# Generated by Django 4.0.2 on 2022-03-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_menuitem_order_menuitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='timeCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
