# Generated by Django 4.0.2 on 2022-03-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_menu_timecreated_alter_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unitType',
            field=models.CharField(choices=[('grams', 'Grams'), ('ounces', 'Ounces'), ('item', 'Item')], default='IT', max_length=200),
        ),
    ]
