# Generated by Django 4.0.2 on 2022-04-15 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0015_ingredient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='inventoryQuantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unitCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unitType',
            field=models.CharField(choices=[('Grams', 'Grams'), ('Ounces', 'Ounces'), ('Pieces', 'Pieces')], max_length=200, verbose_name='Unit'),
        ),
    ]
