# Generated by Django 4.0.2 on 2022-04-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_menu_user_menuitem_user_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='user',
        ),
    ]
