# Generated by Django 4.0.2 on 2022-05-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_ingredientquantity_user_menuitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='user',
        ),
    ]
