# Generated by Django 4.0.2 on 2022-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_ingredientquantity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='inventoryQuantity',
            field=models.CharField(max_length=200, verbose_name='Quantity'),
        ),
    ]
