# Generated by Django 4.0.2 on 2022-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_ingredient_inventoryquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='inventoryQuantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
