# Generated by Django 4.0.2 on 2022-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_remove_ingredientquantity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unitType',
            field=models.CharField(choices=[('Grams', 'Grams'), ('Ounces', 'Ounces'), ('Pieces', 'Pieces'), ('Kilograms', 'Kilograms'), ('Fluid Ounces', 'Fluid Ounces'), ('Milliliters', 'Milliliters'), ('Liters', 'Liters'), ('Loafs', 'Loafs'), ('Cups', 'Cups'), ('Bottles', 'Bottles')], max_length=200, verbose_name='Unit'),
        ),
    ]
